<?xml version="1.0"?>
<doc>
    <assembly>
        <name>SCADtools.Revit.UI.RubberBand</name>
    </assembly>
    <members>
        <member name="T:SCADtools.Revit.UI.DB.XYZPair">
            <summary>
            Represents a pair of points in 3-dimensional space.
            </summary>
            <remarks>
            This class is used to store a start point and an end point, each represented by an
            XYZ coordinate. It can be used to define a segment or a line between two points.
            </remarks>
        </member>
        <member name="P:SCADtools.Revit.UI.DB.XYZPair.StartPoint">
            <summary>
            Gets the 3D start point.
            </summary>
        </member>
        <member name="P:SCADtools.Revit.UI.DB.XYZPair.EndPoint">
            <summary>
            Gets the 3D end point.
            </summary>
        </member>
        <member name="M:SCADtools.Revit.UI.DB.XYZPair.#ctor(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Creates an XYZPair with the supplied points.
            </summary>
            <param name="startPoint"></param>
            <param name="endPoint"></param>
        </member>
        <member name="M:SCADtools.Revit.UI.Extensions.DocumentExtensions.GetFamilySymbolByName(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Retrieves the <see cref="T:FamilySymbol"/> with the specified name from the document.
            </summary>
            <param name="document">The Revit document from which to retrieve the family symbol.</param>
            <param name="symbolName">The name of the family symbol to retrieve.</param>
            <returns>The <see cref="T:FamilySymbol"/> with the specified name, or <c>null</c> if no such symbol is found.</returns>
            <exception cref="T:ArgumentNullException">Thrown when the <paramref name="document"/> is <c>null</c>.</exception>
            <exception cref="T:ArgumentException">Thrown when the <paramref name="symbolName"/> is <c>null</c> or empty.</exception>
        </member>
        <member name="M:SCADtools.Revit.UI.Extensions.UIDocumentExtensions.PickPoints(Autodesk.Revit.UI.UIDocument)">
            <summary>
            Prompts the user to pick two points in the Revit model and returns them as an <see cref="T:SCADtools.Revit.UI.DB.XYZPair"/>.
            </summary>
            <param name="uiDocument">The UIDocument instance representing the current Revit document.</param>
            <returns>An <see cref="T:SCADtools.Revit.UI.DB.XYZPair"/> containing the start and end points selected by the user.</returns>
            <exception cref="T:ArgumentNullException">Thrown when the <paramref name="uiDocument"/> is null.</exception>
            <exception cref="T:InvalidOperationException">Thrown when the FamilySymbol required for picking points cannot be found or loaded.</exception>
        </member>
        <member name="T:SCADtools.Revit.UI.Properties.Resources">
            <summary>
              Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
            </summary>
        </member>
        <member name="P:SCADtools.Revit.UI.Properties.Resources.ResourceManager">
            <summary>
              Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
            </summary>
        </member>
        <member name="P:SCADtools.Revit.UI.Properties.Resources.Culture">
            <summary>
              Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
              búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
            </summary>
        </member>
        <member name="P:SCADtools.Revit.UI.Properties.Resources._RubberBand">
            <summary>
              Busca un recurso adaptado de tipo System.Byte[].
            </summary>
        </member>
        <member name="M:SCADtools.Revit.UI.Services.PressService.OneKey(System.IntPtr,System.Char)">
            <summary>
            Post one single keystroke.
            </summary>
        </member>
        <member name="M:SCADtools.Revit.UI.Services.PressService.Keys(System.String)">
            <summary>
            Post a sequence of keystrokes.
            </summary>
        </member>
    </members>
</doc>
